### ISSUE TITLE
Margin Requirements Help - Non Urgent

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/sections#1]
@thomasjbradley 

I was able to complete this assignment enough to satisfy Markbot, but not without essentially ignoring the requirements on margin width. I was wondering if you could help steer my code in the correct direction, since I assume I over-complicated my styling?

**Comment by thomasjbradley** [comment]
It’s so close!

I think the big problem is that the button shouldn’t be an `<h2>` because it isn’t a heading. It’s only an `<a>` tag, just a plain old link. Because it’s a heading it has extra margins that I think are increasing the height of the right-hand column.

---
A few code adjustments:

1. There should be only 1 `<section>` tag, this whole thing is a single section. No `<header>`, no `<footer>`, etc.
2. There’s `margin` on the `html` element which isn’t ideal, it should be `padding` on the top & bottom of the `<section>` tag.
